"""add_server_reports_table

Revision ID: 1126aebdc103
Revises: 1e96cbcd4665
Create Date: 2026-05-06 04:05:04.523655

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1126aebdc103'
down_revision = '1e96cbcd4665'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
